from __future__ import annotations

from .models import House, Review


DEFAULT_HOUSES = [
    House(
        id="home-rent-001",
        sourceName="demo-public-feed",
        sourceListingId="rent-001",
        sourceUrl="https://example.com/listings/rent-001",
        category="rent",
        intentLabel="租房",
        cityName="北京",
        title="望京南 两居整租",
        communityName="天畅园",
        priceText="5200元/月",
        meta="58平 | 朝南 | 地铁8分钟",
        districtText="朝阳区",
        tags=["近地铁", "整租", "采光好"],
        summary="适合望京和国贸双向通勤，生活配套成熟，适合稳定上班族。",
        scoreText="4.7分",
        highlightTitle="推荐理由",
        highlightText="通勤稳定、生活便利，适合优先考虑效率和舒适度的人群。",
        trafficText="步行8分钟到地铁站，到国贸约28分钟。",
        lifestyleText="周边有商超、菜市场和便利店，日常生活方便。",
        searchText="北京 朝阳区 望京南 两居 整租 近地铁 通勤 采光好 生活配套 成熟小区",
    ),
    House(
        id="home-rent-002",
        sourceName="demo-public-feed",
        sourceListingId="rent-002",
        sourceUrl="https://example.com/listings/rent-002",
        category="rent",
        intentLabel="租房",
        cityName="北京",
        title="回龙观东大街 主卧合租",
        communityName="龙泽苑",
        priceText="3100元/月",
        meta="26平 | 精装 | 地铁12分钟",
        districtText="昌平区",
        tags=["预算友好", "安静", "可做饭"],
        summary="更适合预算敏感用户，兼顾通勤和日常生活便利度。",
        scoreText="4.5分",
        highlightTitle="推荐理由",
        highlightText="预算压力小，适合先稳定住下来的通勤用户。",
        trafficText="地铁12分钟，到西二旗约22分钟。",
        lifestyleText="周边有餐饮和基础商业，适合日常通勤生活。",
        searchText="北京 昌平区 回龙观 合租 主卧 预算友好 安静 可做饭 通勤",
    ),
    House(
        id="home-buy-001",
        sourceName="demo-public-feed",
        sourceListingId="buy-001",
        sourceUrl="https://example.com/listings/buy-001",
        category="buy",
        intentLabel="买房",
        cityName="北京",
        title="回龙观 三居改善",
        communityName="融泽嘉园",
        priceText="268万",
        meta="89平 | 电梯房 | 南北通透",
        districtText="昌平区",
        tags=["学区优先", "医疗配套", "成熟社区"],
        summary="适合家庭长期自住，社区配套完整，生活半径清晰。",
        scoreText="4.6分",
        highlightTitle="推荐理由",
        highlightText="兼顾教育、医疗和社区成熟度，更适合家庭长期居住。",
        trafficText="社区医院步行10分钟，公共交通接驳方便。",
        lifestyleText="成熟小区，公园、餐饮和社区服务半径完整。",
        searchText="北京 昌平区 回龙观 三居 买房 学区 医疗配套 成熟社区 长期自住",
    ),
    House(
        id="home-buy-002",
        sourceName="demo-public-feed",
        sourceListingId="buy-002",
        sourceUrl="https://example.com/listings/buy-002",
        category="buy",
        intentLabel="买房",
        cityName="北京",
        title="通州运河商务区 两居",
        communityName="运河湾",
        priceText="235万",
        meta="76平 | 次新房 | 电梯房",
        districtText="通州区",
        tags=["总价可控", "次新房", "生活配套"],
        summary="适合首次置业，兼顾总价、通勤和商圈便利度。",
        scoreText="4.3分",
        highlightTitle="推荐理由",
        highlightText="总价更容易接受，适合首次置业和自住导向用户。",
        trafficText="近地铁和商圈，通勤与购物便利度较好。",
        lifestyleText="商圈配套齐全，适合追求生活便利的购房人群。",
        searchText="北京 通州区 两居 买房 总价可控 次新房 商圈 生活配套 首次置业",
    ),
]


DEFAULT_REVIEWS = [
    Review(
        id="review-001",
        houseTitle="望京南 两居整租",
        communityName="天畅园",
        score=5,
        livingTags=["安静", "近地铁", "买菜方便"],
        content="晚上整体比较安静，地铁和超市都不远，适合上班族稳定居住。",
        displayName="匿名用户",
        createdAt="2026-03-24 12:30",
    ),
    Review(
        id="review-002",
        houseTitle="回龙观 三居改善",
        communityName="融泽嘉园",
        score=4,
        livingTags=["学区友好", "社区成熟", "医疗方便"],
        content="适合家庭长期居住，社区配套完整，但晚高峰主路会有些堵。",
        displayName="住户反馈",
        createdAt="2026-03-23 20:10",
    ),
]

